repository: SOS-CER/SOS-CER.github.io
baseurl: 
title: Science of Software - Computing Education Research
description: Science of Software - Computing Education Research
github: [metadata]
show_downloads: false
google_analytics:
theme:

markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "comprehensive-exercise"
    values:
      layout: CE-page

collections:         
     projects:
        output: true
     comprehensive-exercise:
        output: true 
     testing:
        output: true
     testing-v6-0-0:
        output: true
     testing-exercise-DE:
        output: true
     testing-exercise-BBT-Triangle:
        output: true
     testing-exercise-BBT:
        output: true
     testing-exercise-WBT:
        output: true
     sssolitaire:
        output: true
     smssolitaire:
        output: true
                 
plugins: ['jekyll-relative-links', 'jekyll/scholar']
  
scholar:
    style: ieee